#!/bin/sh

EXECFILE="$HOME/.config/laer/command"
DEFAULTEDITOR="$HOME/.config/laer/defaulteditor"

if [ ! -f $EXECFILE ]
then
    mkdir $HOME/.config
    mkdir $HOME/.config/laer
    touch $EXECFILE
    echo "
#!/bin/sh
neofetch
    " > $EXECFILE
    chmod a+x $EXECFILE
    clear
fi

if [ ! -f $DEFAULTEDITOR ]
then
    touch $DEFAULTEDITOR
    echo "vim" > $DEFAULTEDITOR
fi

DEFAULTEDITORCOMMAND=$(cat $DEFAULTEDITOR)

if [ ! -z "$1" ]
then
    if [ $1 = "--help" ] || [ $1 = "-h" ]
    then
        echo "clear command but personalized!!!
you can configurate this command to personalize

Commands:
laer [Command]

    --help or -h            Help
    
    --version or -v         See Version
    
    --config or -c          Read Config file
    
    --edit or -e            Edit Config File
    
    --change-editor or -ce   Change Editor
        Use:
        -ce [Editor]    Change to This Editor
        -ce             Ask you the Editor
        
    --reset or -r           Reset to Default
        Use:
        -r editor       Reset just editor
        -r config       Reset just config
        -r all          Reset All
        
    --add-link				add a link to laer
		Use:
		--add-link [link]
"
    fi
    if [ $1 = "--version" ] || [ $1 = "-v" ]
    then
        echo "v0.2-dev"
    fi
    if [ $1 = "--config" ] || [ $1 = "-c" ]
    then
        cat $EXECFILE
    fi
    if [ $1 = "--edit" ] || [ $1 = "-e" ]
    then
        $DEFAULTEDITORCOMMAND $EXECFILE
    fi
    if [ $1 = "--change-editor" ] || [ $1 = "-ce" ]
    then
        if [ ! -z "$2" ]
        then
            echo "$2" > $DEFAULTEDITOR
        else
            echo "What editor you want use"
            read editortemp
            echo "$editortemp" > $DEFAULTEDITOR
        fi
    fi
    if [ $1 = "--reset" ] || [ $1 = "-r" ]
    then
        if [ ! -z "$2" ]
        then
            if [ $2 = "editor" ]
            then
                rm -f $DEFAULTEDITOR
                echo "editor reset!"
            fi
            if [ $2 = "config" ]
            then
                rm -f $EXECFILE
                echo "config reset!"
            fi
            if [ $2 = "all" ]
            then
                rm -f $EXECFILE
                rm -f $DEFAULTEDITOR
                echo "laer reset!"
            fi
        else
            echo "
    --reset or -r           Reset to Default
        Use:
        -r editor       Reset just editor
        -r config       Reset just config
        -r all          Reset All
            "
        fi
    fi
    if [ $1 = "--add-link" ]
    then
		if [ ! -z "$2" ]
		then
		
			if [ -f "/usr/bin/$2" ] || [ -f "/usr/sbin/$2" ]
			then
				echo "$2 is used"
				exit
			fi
			if [ -f "/etc/laer/linked" ]
			then
				echo "$(cat /etc/laer/linked) is linked. You cannot link $2."
				exit
			fi
			echo "Important"
			echo "Are you sure that you want to link laer to $2?"
			echo "This action remove the command $2, if this command exist"
			echo "if you are sure that $2 doesn't exist"
			echo "you can continue"
			echo
			echo
			echo "Are you Sure? (y/n)"
			read addlink
			if [ $addlink = "y" ] || [ $addlink = "Y" ]
			then
				echo "Ok!"
				if [ $(whoami) = "root" ]
				then
					echo "Perfect! You're root"
					
					echo "Enter to continue"
					read continue
					
					mkdir /etc/laer
					echo "$2" > /etc/laer/linked
					
					ln /usr/bin/laer /usr/bin/$2
					
					echo "laer is now linked to $2" 
					
				else
					echo
					echo "You have to run this as root"
				fi
			else
				echo "Aborting"
				exit
			fi
		else
			echo "
    --add-link				add a link to laer
		Use:
		--add-link [link]
			"
		fi
    fi
    exit
fi


clear
$EXECFILE
