#!/bin/bash



if [ -f "/etc/laer/linked" ]
then
    LINKED=$(cat /etc/laer/linked)
    COLINKED=$(cat /usr/bin/$LINKED)
    CORIGINAL=$(cat /usr/bin/laer)
    COOCORTED=${CORIGINAL:0:25}
    COLCORTED=${COLINKED:0:25}
    
	if [[ $COOCORTED = $COLCORTED ]]
	then
        echo "You've been created a link" 
		rm -f /usr/bin/$LINKED
		echo "link removed"
	fi
	rm -f /etc/laer/linked
	echo "link name removed"
fi
echo Laer Removed
